status = INFO
name = HiveLogConfig

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{1.} - %m%n

rootLogger.level = DEBUG
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

#logger.metastore.name = org.apache.hadoop.hive.metastore
#logger.metastore.level = DEBUG
#logger.metastore.additivity = false
#logger.metastore.appenderRefs = console
#logger.metastore.appenderRef.console.ref = console
#
#logger.datanucleus.name = DataNucleus
#logger.datanucleus.level = DEBUG
#logger.datanucleus.additivity = false
#logger.datanucleus.appenderRefs = console
#logger.datanucleus.appenderRef.console.ref = console
#
#logger.hadoop.name = org.apache.hadoop
#logger.hadoop.level = INFO
#logger.hadoop.additivity = false
#logger.hadoop.appenderRefs = console
#logger.hadoop.appenderRef.console.ref = console